# Metricbeat configuration for Stack Monitoring (Elasticsearch + Kibana)

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    # You can specify multiple nodes; Metricbeat will balance between them
    hosts: ["http://elasticsearch-1:9200", "http://elasticsearch-2:9200", "http://elasticsearch-3:9200"]

  - module: kibana
    xpack.enabled: true
    period: 10s
    hosts: ["http://kibana:5601"]

# Output to Elasticsearch (no auth/SSL as per current stack settings)
output.elasticsearch:
  hosts: ["http://elasticsearch-1:9200", "http://elasticsearch-2:9200", "http://elasticsearch-3:9200"]

# Optional: let Metricbeat talk to Kibana for dashboards/setup
setup.kibana:
  host: "http://kibana:5601"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

# Log to file for persistence
logging.to_files: true
logging.files:
  path: /usr/share/metricbeat/logs
  name: metricbeat.log
  keepfiles: 7
  rotateeverybytes: 10485760
logging.level: info
